version: '3.4'

services:
  pt.dockerwebapi:
    image: ${DOCKER_REGISTRY-}ptdockerwebapi
    build:
      context: .
      dockerfile: PT.DockerWebAPI/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=@hrn#321
